name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  shared_preferences: ^2.5.2
  cloud_firestore: ^5.6.5
  crypto: ^3.0.6
  mobile_scanner: ^6.0.7
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  google_generative_ai: ^0.4.6
  page_transition: ^2.2.1
  flutter_animate: ^4.5.2
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
